<?php

namespace OC\PlatformBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertsWithoutApplication($day)
    {
        $qb = $this ->createQueryBuilder('advertskill');

        $qb->delete()
            ->innerJoin('advertskill.advert', 'a')
            ->addSelect('a')
            ->where("DATE_ADD(a.date, :day, 'DAY') <= CURRENT_DATE()")
            ->setParameter('day', $day)
            ->andWhere('a.applications IS EMPTY')//*/
            ;

        return $qb->getQuery()->getResult();
    }
}
